import { Todo } from "../class/todo";

export const todoList: Array<Todo> = [
    new Todo("Buy groceries", "Buy eggs, milk, butter", new Date()),
    new Todo("Complete homework", "Finish DSA assignment", new Date()),
    new Todo("Go to the gym", "Leg day", new Date(new Date().getTime() + 86400000)),
    new Todo("Read a book", "Read at least 50 pages", new Date(new Date().getTime() + 86400000)),
    new Todo("Clean the house", "Vacuum and dust the living room", new Date(new Date().getTime() + 86400000)),
    new Todo("Finish project report", "Complete the final draft", new Date(new Date().getTime() + 86400000)),
    new Todo("Buy groceries", "Get fruits and vegetables", new Date(new Date().getTime() + 86400000)),
    new Todo("Call mom", "Catch up with family", new Date(new Date().getTime() + 86400000)),
    new Todo("Plan vacation", "Book tickets and hotel", new Date(new Date().getTime() + 86400000)),
    new Todo("Attend meeting", "Discuss Q3 results", new Date(new Date().getTime() + 86400000)),
    new Todo("Go for a run", "5km morning run", new Date(new Date().getTime() + 86400000)),
    new Todo("Cook dinner", "Try a new recipe", new Date(new Date().getTime() + 86400000)),
    new Todo("Watch a movie", "Watch a new release", new Date(new Date().getTime() + 86400000)),
    new Todo("Water plants", "Water all indoor plants", new Date(new Date().getTime() + 86400000)),
    new Todo("Write blog post", "Draft an article on productivity", new Date(new Date().getTime() + 86400000)),
    new Todo("Learn a new skill", "Practice coding in Python", new Date(new Date().getTime() + 86400000)),
    new Todo("Pay bills", "Pay electricity and internet bills", new Date(new Date().getTime() + 86400000)),
    new Todo("Attend webinar", "Join the data science webinar", new Date(new Date().getTime() + 86400000)),
    new Todo("Organize desk", "Sort out files and documents", new Date(new Date().getTime() + 86400000)),
    new Todo("Take the car for servicing", "Get the oil changed", new Date(new Date().getTime() + 86400000)),
    new Todo("Meet with friends", "Dinner at a new restaurant", new Date(new Date().getTime() + 86400000)),
    new Todo("Update resume", "Add recent projects", new Date(new Date().getTime() + 86400000)),
    new Todo("Practice guitar", "Learn a new song", new Date(new Date().getTime() + 86400000)),
    new Todo("Meditate", "10 minutes of mindfulness", new Date(new Date().getTime() + 86400000)),
    new Todo("Do laundry", "Wash and fold clothes", new Date(new Date().getTime() + 86400000)),
    new Todo("Read a book", "Finish chapter 3 of my novel", new Date(new Date().getTime() + 86400000)),
    new Todo("Go for a walk", "30-minute walk in the park", new Date(new Date().getTime() + 86400000)),
    new Todo("Call mom", "Check in and say hi", new Date(new Date().getTime() + 86400000)),
    new Todo("Grocery shopping", "Buy essentials for the week", new Date(new Date().getTime() + 86400000)),
    new Todo("Write journal", "Reflect on the day", new Date(new Date().getTime() + 86400000)),
    new Todo("Pay bills", "Electricity and water bills", new Date(new Date().getTime() + 86400000)),
    new Todo("Prepare dinner", "Cook a healthy meal", new Date(new Date().getTime() + 86400000)),
    new Todo("Water plants", "Nourish indoor plants", new Date(new Date().getTime() + 86400000)),
    new Todo("Workout", "30 minutes of cardio", new Date(new Date().getTime() + 86400000)),
    new Todo("Organize desk", "Tidy up workspace", new Date(new Date().getTime() + 86400000)),
    new Todo("Plan weekend", "Set schedule for activities", new Date(new Date().getTime() + 86400000)),
    new Todo("Practice coding", "Solve 3 coding problems", new Date(new Date().getTime() + 86400000)),
    new Todo("Respond to emails", "Reply to important messages", new Date(new Date().getTime() + 86400000)),
    new Todo("Clean kitchen", "Wash dishes and wipe counters", new Date(new Date().getTime() + 86400000)),
    new Todo("Take out trash", "Dispose of garbage", new Date(new Date().getTime() + 86400000)),
    new Todo("Meal prep", "Prepare meals for the week", new Date(new Date().getTime() + 86400000)),
    new Todo("Yoga session", "1-hour yoga class", new Date(new Date().getTime() + 86400000)),
    new Todo("Update resume", "Add recent projects", new Date(new Date().getTime() + 86400000)),
    new Todo("Backup files", "Secure important documents", new Date(new Date().getTime() + 86400000)),
    new Todo("Clean car", "Vacuum and wash exterior", new Date(new Date().getTime() + 86400000)),
    new Todo("Learn a new recipe", "Try cooking something new", new Date(new Date().getTime() + 86400000)),
    new Todo("Volunteer", "Help out at the local shelter", new Date(new Date().getTime() + 86400000)),
    new Todo("Visit a friend", "Catch up with an old friend", new Date(new Date().getTime() + 86400000)),
    new Todo("Watch a documentary", "Learn something new", new Date(new Date().getTime() + 86400000)),
    new Todo("Donate clothes", "Clear out wardrobe", new Date(new Date().getTime() + 86400000)),
    new Todo("Study a new language", "Learn 10 new words", new Date(new Date().getTime() + 86400000)),
    new Todo("Declutter", "Get rid of unnecessary items", new Date(new Date().getTime() + 86400000)),
    new Todo("Meditate", "15 minutes of deep breathing", new Date(new Date().getTime() + 86400000)),
    new Todo("Research a topic", "Spend time learning", new Date(new Date().getTime() + 86400000)),
    new Todo("Write a blog post", "Share knowledge on a topic", new Date(new Date().getTime() + 86400000)),
    new Todo("Plan a trip", "Organize travel itinerary", new Date(new Date().getTime() + 86400000)),
    new Todo("Repair bike", "Fix the flat tire", new Date(new Date().getTime() + 86400000)),
    new Todo("Visit a museum", "Explore new exhibits", new Date(new Date().getTime() + 86400000)),
    new Todo("Catch up on sleep", "Take a power nap", new Date(new Date().getTime() + 86400000)),
    new Todo("Organize photos", "Sort through digital photos", new Date(new Date().getTime() + 86400000)),
    new Todo("Start a new hobby", "Explore something creative", new Date(new Date().getTime() + 86400000)),
    new Todo("Listen to a podcast", "Learn from industry experts", new Date(new Date().getTime() + 86400000)),
];
